const ENUMS = {
    PENDIDIKAN: [
        'AKADEMI/ DIPLOMA III/ SARJANA MUDA',
        'BELUM TAMAT SD/ SEDERAJAT',
        'DIPLOMA I/II',
        'DIPLOMA IV/ STRATA 1',
        'DOKTORAL/ STRATA 3',
        'MAGISTER/ STRATA 2',
        'SLTA/ SEDERAJAT',
        'SLTP/ SEDERAJAT',
        'TAMAT SD/ SEDERAJAT',
        'TIDAK/ BELUM SEKOLAH',
        'LAINNYA'
    ],
    PEKERJAAN: [
        'APARAT DESA/ KECAMATAN',
        'APOTEKER',
        'BELUM/ TIDAK BEKERJA',
        'BURUH HARIAN LEPAS',
        'BURUH NELAYAN/ PERIKANAN',
        'BURUH TANI/ PERKEBUNAN',
        'DOSEN SWASTA',
        'DOKTER',
        'GURU',
        'GURU HONORER',
        'GURU PPPK',
        'IMAM MESJID',
        'KARYAWAN HONORER',
        'KARYAWAN SWASTA',
        'KEPOLISIAN RI (POLRI)',
        'LANJUT USIA (LANSIA)',
        'MENGURUS RUMAH TANGGA',
        'NELAYAN/ PERIKANAN',
        'PA CNI',
        'PARAMEDIK/ BIDAN/ PERAWAT',
        'PEDAGANG',
        'PEGAWAI BUMN/PERSERO',
        'PEGAWAI HONORER',
        'PEGAWAI NEGERI SIPIL (PNS)',
        'PEGAWAI PPPK',
        'PEKERJAAN LAINNYA',
        'PELAJAR/ MAHASISWA',
        'PELAYARAN',
        'PENSIUNAN PNS',
        'PERDAGANGAN',
        'PETANI/ PEKEBUN',
        'PURNAWIRAWAN TNI/ POLRI',
        'SECURITY',
        'SOPIR',
        'TENTARA NASIONAL INDONESIA (TNI)',
        'TUKANG BATU',
        'TUKANG JAHIT',
        'TUKANG KAYU',
        'TUKANG LAS/ PANDAI BESI',
        'VETERAN',
        'WARTAWAN/ JURNALIS',
        'WIRASWASTA',
        'ARTIS',
        'ANGGOTA DEWAN',
        'GURU TPQ',
        'MEKANIK',
        'LAINNYA'
    ],
    STATUS_PERKAWINAN: [
        'BELUM KAWIN',
        'CERAI',
        'CERAI HIDUP',
        'CERAI HIDUP BELUM TERCATAT',
        'CERAI HIDUP TERCATAT',
        'CERAI MATI',
        'CERAI MATI BELUM TERCATAT',
        'CERAI MATI TERCATAT',
        'CERAI TERCATAT',
        'CERAI BELUM TERCATAT',
        'KAWIN',
        'KAWIN BELUM TERCATAT',
        'KAWIN TERCATAT',
        'LAINNYA'
    ],
    HUBUNGAN_KELUARGA: [
        'ANAK',
        'CUCU',
        'FAMILI LAIN',
        'ISTRI',
        'KEPALA KELUARGA',
        'MERTUA',
        'ORANG TUA',
        'SAUDARA KANDUNG',
        'LAINNYA'
    ],
    STATUS_DOMISILI: [
        'PENDUDUK TETAP',
        'WARGA PENDATANG',
        'LAINNYA'
    ],
    STATUS_KEPENDUDUKAN: [
        'AKTIF',
        'TIDAK AKTIF',
        'PINDAH',
        'LAINNYA'
    ]
};

module.exports = ENUMS;
